### ISSUE TITLE
Logo Proposal for BTB

### ISSUE THREAD

**Issue by area55git** [the-AjK/btb#1]
Hello, I wish to cooperate with **BiteTheBot**, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary

[![LOGO_PROPOSAL_FOR_BTB.jpg](https://s18.postimg.cc/prdk8lp5l/LOGO_PROPOSAL_FOR_BTB.jpg)](https://postimg.cc/image/44yjrkql1/)

**Comment by the-AjK** [comment]
Hi @area55git, thank you for your logo proposal.

**BiteTheBot** and its logo is based on [Bender](https://en.wikipedia.org/wiki/Bender_(Futurama)), that's why I actually prefer to keep the current logo which show Bender's eyes and clearly reflect its personality.

Alberto
